//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualizacionStock
    {
        public int ActualizacionStockId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<int> UsuarioReferenciaId { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual UsuarioReferencia UsuarioReferencia { get; set; }
    }
}
