//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arqueo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arqueo()
        {
            this.ArqueoVenta = new HashSet<ArqueoVenta>();
            this.Egreso = new HashSet<Egreso>();
            this.Ingreso = new HashSet<Ingreso>();
            this.Venta = new HashSet<Venta>();
        }
    
        public int ArqueoId { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Faltante { get; set; }
        public Nullable<decimal> Sobrante { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> Agregado { get; set; }
        public Nullable<decimal> Retirado { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public bool Abierto { get; set; }
        public Nullable<decimal> Iniciado { get; set; }
        public Nullable<decimal> Finalizado { get; set; }
        public Nullable<decimal> TotalEfectivo { get; set; }
        public Nullable<int> UsuarioInicioId { get; set; }
        public Nullable<int> UsuarioFinalizoId { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> ArqueoTipoId { get; set; }
    
        public virtual ArqueoTipo ArqueoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoVenta> ArqueoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egreso> Egreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
