//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboProducto
    {
        public int ComboProductoId { get; set; }
        public int ComboId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Activo { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
