//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        public int EgresoId { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> ArqueoId { get; set; }
        public string Motivo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Arqueo Arqueo { get; set; }
    }
}
