//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DistribuidoraDBEntities : DbContext
    {
        public DistribuidoraDBEntities()
            : base("name=DistribuidoraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActualizacionStock> ActualizacionStock { get; set; }
        public virtual DbSet<Anio> Anio { get; set; }
        public virtual DbSet<ArqueoVenta> ArqueoVenta { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<ComboProducto> ComboProducto { get; set; }
        public virtual DbSet<CondicionIVA> CondicionIVA { get; set; }
        public virtual DbSet<Deposito> Deposito { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilUsuario> PerfilUsuario { get; set; }
        public virtual DbSet<PersonaTipo> PersonaTipo { get; set; }
        public virtual DbSet<PrecioLista> PrecioLista { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<SucursalUsuario> SucursalUsuario { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TipoCobro> TipoCobro { get; set; }
        public virtual DbSet<TipoDuracion> TipoDuracion { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
        public virtual DbSet<TipoStock> TipoStock { get; set; }
        public virtual DbSet<TipoVenta> TipoVenta { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Combo> Combo { get; set; }
        public virtual DbSet<Lista> Lista { get; set; }
        public virtual DbSet<StockDeposito> StockDeposito { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Egreso> Egreso { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<VentaDetalle> VentaDetalle { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Arqueo> Arqueo { get; set; }
        public virtual DbSet<ArqueoTipo> ArqueoTipo { get; set; }
        public virtual DbSet<Dolar> Dolar { get; set; }
        public virtual DbSet<NotaCreditoDetalle> NotaCreditoDetalle { get; set; }
        public virtual DbSet<Remito> Remito { get; set; }
        public virtual DbSet<Transportista> Transportista { get; set; }
        public virtual DbSet<NotaCredito> NotaCredito { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<UsuarioReferencia> UsuarioReferencia { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
    }
}
