//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilUsuario
    {
        public int PerfilUsuarioId { get; set; }
        public int PerfilId { get; set; }
        public int UsuarioId { get; set; }
        public bool Activo { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual UsuarioReferencia UsuarioReferencia { get; set; }
    }
}
