//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ComboProducto = new HashSet<ComboProducto>();
            this.NotaCreditoDetalle = new HashSet<NotaCreditoDetalle>();
            this.PrecioLista = new HashSet<PrecioLista>();
            this.StockDeposito = new HashSet<StockDeposito>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int ProductoId { get; set; }
        public int TipoProductoId { get; set; }
        public int TipoDuracionId { get; set; }
        public int MarcaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PrecioCosto { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Minimo { get; set; }
        public string Codigo { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> ProveedorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComboProducto> ComboProducto { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCreditoDetalle> NotaCreditoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioLista> PrecioLista { get; set; }
        public virtual TipoDuracion TipoDuracion { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDeposito> StockDeposito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
