//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Remito()
        {
            this.NotaCredito = new HashSet<NotaCredito>();
        }
    
        public int RemitoId { get; set; }
        public int ClienteId { get; set; }
        public int VentaId { get; set; }
        public string Fecha { get; set; }
        public string Domicilio { get; set; }
        public Nullable<int> TransportistaId { get; set; }
        public string CUIT { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Transportista Transportista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCredito> NotaCredito { get; set; }
        public virtual UsuarioReferencia UsuarioReferencia { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
