//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDeposito
    {
        public int StockDepositoId { get; set; }
        public int DepositoId { get; set; }
        public int TipoStockId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> ComboId { get; set; }
        public decimal Cantidad { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<decimal> CantidadUsada { get; set; }
        public bool Activo { get; set; }
    
        public virtual Combo Combo { get; set; }
        public virtual Deposito Deposito { get; set; }
        public virtual TipoStock TipoStock { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
