//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class SucursalUsuario
    {
        public int SucursalUsuarioId { get; set; }
        public int SucursalId { get; set; }
        public int UsuarioId { get; set; }
        public bool Activo { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
        public virtual UsuarioReferencia UsuarioReferencia { get; set; }
    }
}
