//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public int VentaId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Codigo { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
