//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.ArqueoVenta = new HashSet<ArqueoVenta>();
            this.Factura = new HashSet<Factura>();
            this.NotaCredito = new HashSet<NotaCredito>();
            this.Remito = new HashSet<Remito>();
            this.Ticket = new HashSet<Ticket>();
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int VentaId { get; set; }
        public int TipoVentaId { get; set; }
        public int SucursalId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public int TipoCobroId { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Final { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Observaciones { get; set; }
        public string DireccionEnvio { get; set; }
        public Nullable<decimal> CostoEnvio { get; set; }
        public bool Pendiente { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<decimal> Recargo { get; set; }
        public Nullable<int> ArqueoId { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public Nullable<decimal> Promos { get; set; }
        public Nullable<decimal> NotaCreditoMonto { get; set; }
        public Nullable<int> PreventistaId { get; set; }
    
        public virtual Arqueo Arqueo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArqueoVenta> ArqueoVenta { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaCredito> NotaCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remito> Remito { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual TipoCobro TipoCobro { get; set; }
        public virtual TipoVenta TipoVenta { get; set; }
        public virtual UsuarioReferencia UsuarioReferencia { get; set; }
        public virtual UsuarioReferencia UsuarioReferencia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
